# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCBZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('train', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('work_time', models.FloatField()),
                ('work_bonus', models.FloatField()),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('rest_time', models.FloatField()),
                ('rest_bonus', models.FloatField()),
                ('sum_bonus', models.FloatField()),
            ],
        ),
    ]
